name: SlimeTECH
version: 1.0.0
main: com.slimetech.SlimeTECH
api-version: '1.16'
author: YourName
description: Tech & Magic plugin with auto-version adaptation

commands:
  slimetch:
    description: Main SlimeTECH command
    usage: /<command> [give|version|info|items|migrate]
    aliases: [st, tech]