name: SlimeTECH
version: 1.0.1-DEV
main: com.slimetech.SlimeTECH
api-version: '1.17'
author: YourName
description: Tech & Magic with version adaptation

commands:
  slimetch:
    description: Main SlimeTECH command
    usage: /<command> [copper|version|transform|guide|open-guide|gui|help]
    aliases: [st, tech]
    
permissions:
  slimetch.*:
    description: All SlimeTECH permissions
    default: op
    children:
      slimetch.copper: true
      slimetch.version: true
      slimetch.transform: true
      slimetch.guide: true
      slimetch.gui: true
      slimetch.help: true
      slimetch.craft: true
      slimetch.magic: true
      slimetch.tech: true
  slimetch.user:
    description: Basic user permissions
    default: true
    children:
      slimetch.guide: true
      slimetch.gui: true
      slimetch.help: true